### ISSUE TITLE
Write an introduction blog post about you

### ISSUE THREAD

**Issue by fharper** [mindee/devrel#141]
Write an introduction blog post about you. See https://blog.mindee.com/fred/ as one example.

**Comment by fharper** [comment]
Let me know when it's ready in WordPress, it would be nice to be able to publish it tomorrow :)

**Comment by fakela** [comment]
Its ready in WordPress

**Comment by fakela** [comment]
> Let me know when it's ready in WordPress, it would be nice to be able to publish it tomorrow :)

It's ready in WordPress

**Comment by fharper** [comment]
Published at https://blog.mindee.com/favour/
