### ISSUE TITLE
Test & update the documentation on curl boundary

### ISSUE THREAD

**Issue by fharper** [mindee/devrel#145]
Test & update the documentation on curl boundary: `boundary=----WebKitFormBoundary`: we may not need it anymore.

**Comment by fakela** [comment]
Is there a new update rolling out that will cease the use of the curl boundary.

**Comment by fharper** [comment]
No, but seems like we may not need it based on what @thentgesMindee wrote on Slack. Just need to test it.

**Comment by fharper** [comment]
I did it, just need to merge the PR once approved.
