### ISSUE TITLE
Define the newsletter format

### ISSUE THREAD

**Issue by fharper** [mindee/devrel#154]
Define the newsletter format like you've done for the November newsletter so we always have the same template and know which informations to gather each month. It'll help people suggest topics too.

**Comment by fakela** [comment]
We have addressed this issue, i would go ahead and close it

**Comment by fakela** [comment]
This has been worked on I think we should close it @fharper

**Comment by fharper** [comment]
You can close it once we merge https://github.com/mindee/devrel/pull/227 :D
