### ISSUE TITLE
Review the "Optical Character Recognition" blog post

### ISSUE THREAD

**Issue by fharper** [mindee/devrel#183]
Review the [Optical Character Recognition](https://docs.google.com/document/d/1NeyqQyuNEwI4r__poDtYLSFUQvbJYhkuFBfC7OJvZj8/edit#heading=h.gxx6dpkxlp5s) blog post

**Comment by fakela** [comment]
I started this on Friday and completed it today. Jonathan has gone through some of the suggestions on Friday. So i will close this cause its done

**Comment by fharper** [comment]
I reviewed it also!
