### ISSUE TITLE
Create a template or architecture for integration documentation

### ISSUE THREAD

**Issue by fharper** [mindee/devrel#224]
Create a template or architecture for integration documentation so they always have the same structure. I need that for a tool who integrated us, they will write the documentation for our site that we will review before publishing, but they want to be sure it fit in our documentation properly.

I guess something like:
- Introduction to the integration
- Benefits
- How to install/Create account
- Code demo (or how to use if no or low code)
- Resources

**Comment by fharper** [comment]
@fakela if you can prioritize this. I'm not sure if I'm clear, so we can discuss this tomorrow.

**Comment by fakela** [comment]
So I agree with the structure, here is a suggestion 

- Introduction to the integration
- Benefits (why do users need to use the integration) Optionally, this can be merged with the introduction if its not long
- Prerequisite(if any)
- How to install/Create account (Getting Started)
- Code demo (or how to use if no or low code)(add screenshots where needed)
- Troubleshoot/ Error management(if any)
- Resources/References

**Comment by fharper** [comment]
Perfect, can you add it in the `documentation.md` once you accept and merge this PR https://github.com/mindee/devrel/pull/233

**Comment by fakela** [comment]
> Perfect, can you add it in the `documentation.md` once you accept and merge this PR #233

Sure 🚀
