### ISSUE TITLE
Create a video for Model Training Page

### ISSUE THREAD

**Issue by fakela** [mindee/devrel#225]
Create a video or a gif for Model Training Page

**Comment by fharper** [comment]
I closed one you created this morning since it was a duplicate of #186. I'll close #186 but let's try to avoid duplicates.

**Comment by fakela** [comment]
> I closed one you created this morning since it was a duplicate of #186. I'll close #186 but let's try to avoid duplicates.

I kept missing the initial one you created. I need glasses 😅. I had to scroll all the way down to see it.
