### ISSUE TITLE
Doc: update Make your request section

### ISSUE THREAD

**Issue by fakela** [mindee/devrel#228]
Update the "prerequisite" in "Make your first request section"  in the documentation https://developers.mindee.com/docs/make-your-first-request

**Comment by fharper** [comment]
Can you add details on what you want to edit please?

**Comment by fakela** [comment]
@fharper Here is the suggested edit https://dash.readme.com/project/mindee/v1.0/suggested/update/61a8f7c6175341005b15fdda
