### ISSUE TITLE
Doc: Update create an API Key section

### ISSUE THREAD

**Issue by fakela** [mindee/devrel#229]
Update "create an API Key" section in the documentation by dividing it into numbered task https://developers.mindee.com/docs/make-your-first-request#create-an-api-key

**Comment by fakela** [comment]
@fharper here is the suggested https://dash.readme.com/project/mindee/v1.0/suggested/update/61a903d16af07903262521c8

**Comment by fharper** [comment]
🤬 
<img width="1020" alt="CleanShot 2021-12-02 at 15 47 44@2x" src="https://user-images.githubusercontent.com/1170989/144500540-1d17f60b-39ed-4eca-8ca8-1e734bd534d6.png">

**Comment by fakela** [comment]
> 🤬 <img alt="CleanShot 2021-12-02 at 15 47 44@2x" width="1020" src="https://user-images.githubusercontent.com/1170989/144500540-1d17f60b-39ed-4eca-8ca8-1e734bd534d6.png">

**Comment by fakela** [comment]
> 🤬 <img alt="CleanShot 2021-12-02 at 15 47 44@2x" width="1020" src="https://user-images.githubusercontent.com/1170989/144500540-1d17f60b-39ed-4eca-8ca8-1e734bd534d6.png">

I could not edit any longer i had to close it and create a new suggestion

**Comment by fakela** [comment]
This is merged https://developers.mindee.com/docs/make-your-first-request#create-an-api-key
