### ISSUE TITLE
Newsletter word count

### ISSUE THREAD

**Issue by fakela** [mindee/devrel#264]
Discuss with Fred on the newsletter word count and define that in our newsletter section

**Comment by fharper** [comment]
There is no word count, it's a guessing game mostly about the email size, so images, link, CSS, HTML... everything can make us go from seeing the full email, to have gmail cut it out with the "click to read more" so it's important that even if we modify the smallest thing, that we send a test email before sending the latest version. I search on the topic, and it seems like knowing how not to have your email cut is a black box, nobody knows, it's just about testing.
