### ISSUE TITLE
Documentation timeline

### ISSUE THREAD

**Issue by fakela** [mindee/devrel#281]
This is a timeline for the documentation milestone in the first quarter of the year. This may be subject to adjustments and revisions.

- [ ] Week 1: Review getting started section
- [ ] Week 2: Review Mindee's REST API section
- [ ] Week 3 and 4: Review OFF-THE-SHELF API section
- [ ] Week 5,6 and 7: Review the APi Builder section
- [ ] Week 8 and 9: Review the integration section

**Comment by fharper** [comment]
What is **Create a tutorial on how to use the Mindee API**? Don't have some already in the doc?

Also, can you be more specific **Read through the docs and make changes where necessary,** like a timeline plan to help us focus and see where it's going. Something like:
Week 1: Review getting started section
Week 2: Review Mindee's REST API section
...

Maybe creating the issues for each of these steps or even pages: seems overkill, but it would be nice to have in the milestones, and see that we are making progress.
