### ISSUE TITLE
Fix Sendgrid rewriting URL for tracking with HTTP

### ISSUE THREAD

**Issue by fharper** [mindee/devrel#38]
Fix Sendgrid rewriting URL for tracking with HTTP (why, it's 2021!!!!)

**Comment by thentgesMindee** [comment]
DevOps team should be currently investigating this

**Comment by Jedylemindee** [comment]
Should be resolved today, I'm seeing this with sendgrid support

**Comment by fharper** [comment]
Awesome, thanks!

**Comment by Jedylemindee** [comment]
Issue should now be resolved, you may close it if it's working for everybody

**Comment by fharper** [comment]
LGTM
