### ISSUE TITLE
Add missing headers images

### ISSUE THREAD

**Issue by fharper** [mindee/devrel#39]
Can you add featured images for these posts please:
- https://test.fred.dev/how-to-design-and-deploy-your-first-document-parsing-api/
- https://test.fred.dev/parsing-receipts-with-mindees-machine-learning-api/
- https://test.fred.dev/extract-receipt-data-with-mindees-api-using-python/
- https://test.fred.dev/extending-license-plate-extraction/
- https://test.fred.dev/parsing-passports-with-mindees-api/

**Comment by dougsillars** [comment]
added. for all but the first post. This post is not published and is *very* out of date.
For that post, I added a category of "unpublished"

**Comment by dougsillars** [comment]
@fharper Verify and close.

**Comment by fharper** [comment]
LGTM
