### ISSUE TITLE
Evaluate README.io as our documentation platform

### ISSUE THREAD

**Issue by fharper** [mindee/devrel#43]
README doesn't seem to be the platform we need. We already had issues with simple things like merging 4 small modifications in one page, and it doesn't handle dynamic documentation like for the API builder...

**README.IO pros**
- our documentation have excellent SEO thanks to their SEO work/optimization (from @jonathanMindee) *

**README.IO cons**
- impossible to do more than small changes in the interface: at some point the system lost it, and you cannot merge the changes (known issue, not the goal of README: see this tweet from the founder https://twitter.com/gkoberger/status/1503459647503712256)
- impossible to do a lot of back and forth, even for small changes: same result at the previous point.
- depending on a sync app since we now use markdown in GitHub (was done because editing in README.IO is a pain when more than one person use it or if there is too many changes)
- responsive UI is bad: mobile experience sucks
- No API to add or update image files, which make the process more tedeious specially since we use markdown in GitHub
- Problem reordering categories in the interface
- Unpublishing page do not unpublished them, but just removed them from the left menu
- API is down or unresponsive a bit too often
- They add a GUI on filenames which is kinda ugly when you download a receipt demo file as one example
- Cannot host assets other than images, like a invoice PDF example. Need to host elsewhere, and link in the documentation
- Google Analytics integration isn't in the head as it should, so it's impossible to validate the ownership of this subdomain with Google Search Console

**README.io uncertainties**
- Not sure we can easily integrate the platform documentation in it since we don't own the platform.

* I would be curious if it's the case because of their SEO implementations, or if it's our content that get us good SEO points. Lastly, searching a terms in our browser and being in top results doesn't mean our SEO is good. The results people get is called `personalized search` results, which is based on your browser/search history, locations, device, mac address, and a lot more things.

I suggest we move to [Docusaurus](https://docusaurus.io/). As much as I'm not a fan of Facebook, this is probably the best documentation platform out there, and hosting it ourselves will give us more opportunities to do what we need to do. In addition to having our documentation content on GitHub with a CI/CD pipeline, it will make it easier to:
- Enforce rules for our documentation;
- Any technical folks to use their actual Git skills to help with the documentation;
- Let anyone from our community easily do PR;
- Since it's OSS and we host it, let us do more than with a SaaS like README.

In any cases, it's not a decision to take lightly, we need to take the time to validate the pros and cons of some platforms.

**Comment by fharper** [comment]
We may want to revisit that in a near future, but for now #221 may do the trick

**Comment by fharper** [comment]
Starting a list that will help us in our future decision

**README.IO pros**
- our documentation have excellent SEO thanks to their SEO work/optimization (from @jonathanMindee) *
- they have an API, which means that our interaction with their web application is now limited

**README.IO cons**
- depending on a sync app since we now use markdown in GitHub (was done because editing in README.IO is a pain when more than one person use it or if there is too many changes)
- responsive UI is bad
- No API to add or update image files, which make the process more tedeious specially since we use markdown in GitHub

**README.io uncertainties**
- Not sure we can easily integrate the platform documentation in it since we don't own the platform.

* I would be curious if it's the case because of their SEO implementations, or if it's our content that get us good SEO points. Also, we should be able to replicate that with the help of a SEO expert.

**Comment by ianardee** [comment]
Using React to power a documentation site seems a bit... excessive.
Honest question: how much JS do you need to download just to view a page?

Some things that are important to me:
* Generate content from docstrings.
* Have diagrams and flowcharts embedded in the documentation (IOW not images)
* Handle several versions of the documentation, at least for the client libraries
* Composable: allow various repos to be pulled together to make a master project
* Customizable: make/change themes, add JS code as needed.
* Searchable
* Integration in CI/CD pipeline
* Can generate locally
* OSS

Bonus:
* Generate PDFs
* Math formula support

I've used Sphinx in the past (mainly as content creator) for technical documentation and it works pretty well.
In any case, all points above are handled.

Downside is that it can be a bit of pain to set up, it's geared towards developers.

Upside for some (like me), downside for others is that it's Python/rst based. This does mean it's used a lot in the scientific and ML communities.

Some examples:
* https://mindee.github.io/doctr/  :wink: 
* https://docs.couchdb.org/en/stable/
* https://docs.ansible.com/
* https://matplotlib.org/stable/index.html
* https://scikit-learn.org/stable/auto_examples/index.html

**Comment by fharper** [comment]
@jonathanMindee there is no other discussions about the documentation platform than here. It's not even something we are thinking of right now, more than a place to write some ideas, and the pros and cons of using README so when the time will come to re-evaluate (or not), we'll have as much data as possible.

**Comment by fharper** [comment]
Here is a blog post an ex-colleague wrote when their startup decided to move away from README.io: it doesn't state the reasons, more than explaining the reasons why they choose next.js.

https://www.daily.co/blog/building-dailys-custom-docs-platform-with-next-js/

**Comment by fharper** [comment]
For history sake, one that Emmanuelle found: https://www.theneo.io/

**Comment by fharper** [comment]
A decision was made that we won't move out from README.io
