### ISSUE TITLE
Create March newsletter

### ISSUE THREAD

**Issue by fakela** [mindee/devrel#458]

**Comment by fharper** [comment]
Add a job section listing the open roles we have. Let's do it with a twist of "if you know someone" so we don't look like we are trying to pooch our customers employees, which is not what we want to do anyway.

**Comment by fharper** [comment]
Add the Node.js new versions information. Don't know if it's worth a blog post, we can check.

**Comment by fharper** [comment]
I swear I'll publish @thentgesMindee blog post before we send the newsletter, so let's add it to it once it's done :)

**Comment by fharper** [comment]
New free Machine Learning course https://www.edx.org/course/google-ai-for-javascript-developers-with-tensorflowjs

**Comment by fakela** [comment]
> Add the Node.js new versions information. Don't know if it's worth a blog post, we can check.

we could link to the documentation since it's already written and updated
