### ISSUE TITLE
Define the newsletter process

### ISSUE THREAD

**Issue by fharper** [mindee/devrel#52]
Define the newsletter process

Here some notes I took last time
> The process will be more fluid next time. Will write a draft on Friday or Monday, will ask people to review on Tuesday, will send a test on Wednesday and will send the newsletter to our customers on Thursday.

**Comment by fakela** [comment]
I think this issue has been addressed as we have a newsletter guide

**Comment by fharper** [comment]
It would be nice to add a section about deadlines so it's clear to everyone since we depend on others for content.

I'm thinking about
- End of first week of the month, we need content propositions
- Second week of the month, we write blog post if needed
- Third week of the month we draft the newsletter, send test
- Fourth week, we send the newsletter

What do you think?

**Comment by fakela** [comment]
> It would be nice to add a section about deadlines so it's clear to everyone since we depend on others for content.
> 
> I'm thinking about
> 
> * End of first week of the month, we need content propositions
> * Second week of the month, we write blog post if needed
> * Third week of the month we draft the newsletter, send test
> * Fourth week, we send the newsletter
> 
> What do you think?
This sounds great! Having this gives a more defined process of what we have to do.

**Comment by fakela** [comment]
I would add this to the newsletter section here.

**Comment by fharper** [comment]
Yep, please do.
