### ISSUE TITLE
code continuity:  sample code should use SDKs

### ISSUE THREAD

**Issue by dougsillars** [mindee/devrel#71]
Would it be possiible to use SDK code for Pythoin and NodeJS in the Documentation sections on platform.mindee.com?

For example:
https://platform.mindee.com/apishub/products/mindee/expense_receipts?setup=default#documentation
![image](https://user-images.githubusercontent.com/1514288/134604097-03a86da6-cdd2-411c-9f56-4ff42931afd7.png)

There's nothing materially incorrect here - but the SDK is easier to use, so we should promote it everywhere we can.

**Comment by fharper** [comment]
I think we should have both, putting the SDK one before, WDYT?

@jonathanMindee ^

**Comment by fharper** [comment]
Duplicate of the issues in the documentation repo
